// Package event defines the EPCIS 2.0 JSON event and document structures
// generated by the engine. Only semantics-supported fields are emitted.
package event

// EPCISEvent is a closed union of the supported EPCIS 2.0 event types.
type EPCISEvent struct {
	Type string `json:"type"` // ObjectEvent | TransformationEvent | AggregationEvent | TransactionEvent | AssociationEvent

	EventID             string `json:"eventID,omitempty"`
	EventTime           string `json:"eventTime"`           // RFC3339
	EventTimeZoneOffset string `json:"eventTimeZoneOffset"` // e.g. "+05:30"
	Action              string `json:"action,omitempty"`    // ADD/OBSERVE/DELETE (Object/Aggregation/Association/Transaction)
	BizStep             string `json:"bizStep,omitempty"`
	Disposition         string `json:"disposition,omitempty"`

	EPCList             []string          `json:"epcList,omitempty"`
	QuantityElementList []QuantityElement `json:"quantityList,omitempty"`

	ParentID          string            `json:"parentID,omitempty"`
	ChildEPCs         []string          `json:"childEPCs,omitempty"`
	ChildQuantityList []QuantityElement `json:"childQuantityList,omitempty"`

	BizTransactionList []BizTransaction `json:"bizTransactionList,omitempty"`

	// TransformationEvent specifics (EPCIS 2.0: inputEPCList/outputEPCList or
	// inputQuantityList/outputQuantityList).
	InputEPCList       []string          `json:"inputEPCList,omitempty"`
	OutputEPCList      []string          `json:"outputEPCList,omitempty"`
	InputQuantityList  []QuantityElement `json:"inputQuantityList,omitempty"`
	OutputQuantityList []QuantityElement `json:"outputQuantityList,omitempty"`
	TransformationID   string            `json:"transformationID,omitempty"`

	// WHERE
	BizLocation *BizLocation `json:"bizLocation,omitempty"`

	// Engine-side metadata, never serialized into the EPCIS document.
	Domain    string `json:"-"`
	SourceRef string `json:"-"`
}

// QuantityElement is an EPCIS quantity element (class-level EPC + quantity).
type QuantityElement struct {
	EPCClass string   `json:"epcClass"`
	Quantity *float64 `json:"quantity,omitempty"`
	UOM      string   `json:"uom,omitempty"`
}

// BizTransaction is an EPCIS business transaction reference (EPCIS 2.0 JSON:
// {"type": ..., "bizTransaction": ...}).
type BizTransaction struct {
	Type           string `json:"type,omitempty"`
	BizTransaction string `json:"bizTransaction"`
}

// BizLocation is the EPCIS business location (WHERE).
type BizLocation struct {
	ID string `json:"id"`
}

// Document is an EPCIS 2.0 document (EPCISDocument).
type Document struct {
	Context       []interface{} `json:"@context"`
	Type          string        `json:"type"`
	SchemaVersion string        `json:"schemaVersion"`
	CreationDate  string        `json:"creationDate"`
	EPCISBody     EPCISBody     `json:"epcisBody"`
}

// EPCISBody holds the event list.
type EPCISBody struct {
	EventList []EPCISEvent `json:"eventList"`
}

// NewDocument creates an EPCIS 2.0 document shell.
func NewDocument(creationDate string) *Document {
	return &Document{
		Context:       []interface{}{"https://ref.gs1.org/epcis/epcis-context.jsonld"},
		Type:          "EPCISDocument",
		SchemaVersion: "2.0",
		CreationDate:  creationDate,
		EPCISBody:     EPCISBody{EventList: []EPCISEvent{}},
	}
}
