package resolver

// GetRelationshipCatalog returns the complete list of 106 documented entity relationships
// categorized across 13 functional groups.
func GetRelationshipCatalog() []RelationshipMetadata {
	return []RelationshipMetadata{
		// 1. Planning & MRP
		{
			ID:               1,
			GroupNumber:      1,
			GroupName:        "1. Planning & MRP",
			SourceEntity:     "Planning Requirement",
			TargetEntity:     "Planning Requirement data",
			JoinType:         "INNER JOIN",
			LogicDescription: "PBIM.BDZEI = PBED.BDZEI",
		},
		{
			ID:               2,
			GroupNumber:      1,
			GroupName:        "1. Planning & MRP",
			SourceEntity:     "Planned Order",
			TargetEntity:     "Process Order",
			JoinType:         "LEFT JOIN",
			LogicDescription: "PLAF.PLNUM = AFPO.PLNUM -> AFPO.AUFNR",
		},
		{
			ID:               3,
			GroupNumber:      1,
			GroupName:        "1. Planning & MRP",
			SourceEntity:     "Planned Order",
			TargetEntity:     "Reservation",
			JoinType:         "LEFT JOIN",
			LogicDescription: "PLAF.RSNUM = RESB.RSNUM",
		},
		{
			ID:               4,
			GroupNumber:      1,
			GroupName:        "1. Planning & MRP",
			SourceEntity:     "Planned Order",
			TargetEntity:     "Process Order",
			JoinType:         "LEFT JOIN",
			LogicDescription: "PLAF.AUFNR = AFPO.AUFNR when PLAF.AUFNR is populated",
		},

		// 2. Process Order Structure
		{
			ID:               5,
			GroupNumber:      2,
			GroupName:        "2. Process Order Structure",
			SourceEntity:     "Process Order",
			TargetEntity:     "Process Order Header",
			JoinType:         "INNER JOIN",
			LogicDescription: "AFKO.AUFNR = ProcessOrder.AUFNR",
		},
		{
			ID:               6,
			GroupNumber:      2,
			GroupName:        "2. Process Order Structure",
			SourceEntity:     "Process Order",
			TargetEntity:     "Process Order Item",
			JoinType:         "INNER JOIN",
			LogicDescription: "AFPO.AUFNR = ProcessOrder.AUFNR",
		},
		{
			ID:               7,
			GroupNumber:      2,
			GroupName:        "2. Process Order Structure",
			SourceEntity:     "Process Order",
			TargetEntity:     "Reservation",
			JoinType:         "LEFT JOIN",
			LogicDescription: "AFKO.RSNUM = RESB.RSNUM AND RESB.AUFNR = AFKO.AUFNR when populated",
		},
		{
			ID:               8,
			GroupNumber:      2,
			GroupName:        "2. Process Order Structure",
			SourceEntity:     "Reservation",
			TargetEntity:     "Material Consumption",
			JoinType:         "LEFT JOIN",
			LogicDescription: "RESB.RSNUM = MATDOC.RSNUM AND RESB.RSPOS = MATDOC.RSPOS AND MATDOC.BWART = 261",
		},
		{
			ID:               9,
			GroupNumber:      2,
			GroupName:        "2. Process Order Structure",
			SourceEntity:     "Process Order",
			TargetEntity:     "Material Consumption",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MATDOC.AUFNR = AFKO.AUFNR AND MATDOC.BWART = 261",
		},
		{
			ID:               10,
			GroupNumber:      2,
			GroupName:        "2. Process Order Structure",
			SourceEntity:     "Process Order",
			TargetEntity:     "Production Confirmation",
			JoinType:         "LEFT JOIN",
			LogicDescription: "AFRU.AUFNR = AFKO.AUFNR",
		},
		{
			ID:               11,
			GroupNumber:      2,
			GroupName:        "2. Process Order Structure",
			SourceEntity:     "Production Confirmation",
			TargetEntity:     "Process Operation",
			JoinType:         "INNER JOIN",
			LogicDescription: "AFRU.AUFPL = AFVC.AUFPL AND AFRU.APLZL = AFVC.APLZL",
		},
		{
			ID:               12,
			GroupNumber:      2,
			GroupName:        "2. Process Order Structure",
			SourceEntity:     "Process Order",
			TargetEntity:     "Process Operation",
			JoinType:         "INNER JOIN",
			LogicDescription: "AFKO.AUFPL = AFVC.AUFPL",
		},
		{
			ID:               13,
			GroupNumber:      2,
			GroupName:        "2. Process Order Structure",
			SourceEntity:     "Process Operation",
			TargetEntity:     "Work Center",
			JoinType:         "INNER JOIN",
			LogicDescription: "AFVC.ARBID = CRHD.OBJID",
		},
		{
			ID:               14,
			GroupNumber:      2,
			GroupName:        "2. Process Order Structure",
			SourceEntity:     "Process Order",
			TargetEntity:     "Work Center",
			JoinType:         "INNER JOIN",
			LogicDescription: "AFKO.AUFPL = AFVC.AUFPL -> AFVC.ARBID = CRHD.OBJID",
		},

		// 3. Quality Management
		{
			ID:               15,
			GroupNumber:      3,
			GroupName:        "3. Quality Management",
			SourceEntity:     "Process Order",
			TargetEntity:     "Quality Inspection Lot",
			JoinType:         "LEFT JOIN",
			LogicDescription: "Prefer AFKO.PRUEFLOS = QALS.PRUEFLOS; otherwise AFKO.AUFNR = QALS.AUFNR when populated",
		},
		{
			ID:               16,
			GroupNumber:      3,
			GroupName:        "3. Quality Management",
			SourceEntity:     "Quality Inspection Lot",
			TargetEntity:     "Material Movement",
			JoinType:         "LEFT JOIN",
			LogicDescription: "QALS.MBLNR = MATDOC.MBLNR AND QALS.MJAHR = MATDOC.MJAHR AND QALS.ZEILE = MATDOC.ZEILE",
		},
		{
			ID:               17,
			GroupNumber:      3,
			GroupName:        "3. Quality Management",
			SourceEntity:     "Quality Inspection Lot",
			TargetEntity:     "Batch",
			JoinType:         "LEFT JOIN",
			LogicDescription: "QALS.MATNR = Batch.MATNR AND QALS.WERK = Batch.WERKS AND QALS.CHARG = Batch.CHARG",
		},
		{
			ID:               18,
			GroupNumber:      3,
			GroupName:        "3. Quality Management",
			SourceEntity:     "Quality Inspection Lot",
			TargetEntity:     "Sampling",
			JoinType:         "LEFT JOIN",
			LogicDescription: "QALS.PRUEFLOS = QAMR.PRUEFLOS / QASR.PRUEFLOS",
		},
		{
			ID:               19,
			GroupNumber:      3,
			GroupName:        "3. Quality Management",
			SourceEntity:     "Sampling",
			TargetEntity:     "Inspection Result",
			JoinType:         "LEFT JOIN",
			LogicDescription: "Match PRUEFLOS plus the relevant operation/characteristic keys",
		},
		{
			ID:               20,
			GroupNumber:      3,
			GroupName:        "3. Quality Management",
			SourceEntity:     "Quality Inspection Lot",
			TargetEntity:     "Usage Decision",
			JoinType:         "LEFT JOIN",
			LogicDescription: "QALS.PRUEFLOS = QAVE.PRUEFLOS",
		},

		// 4. Material Movements & Inventory Postings
		{
			ID:               21,
			GroupNumber:      4,
			GroupName:        "4. Material Movements & Inventory Postings",
			SourceEntity:     "Material Movement",
			TargetEntity:     "Material",
			JoinType:         "INNER JOIN",
			LogicDescription: "MATDOC.MATNR = MARA.MATNR",
		},
		{
			ID:               22,
			GroupNumber:      4,
			GroupName:        "4. Material Movements & Inventory Postings",
			SourceEntity:     "Material Movement",
			TargetEntity:     "Plant Material",
			JoinType:         "INNER JOIN",
			LogicDescription: "MATDOC.MATNR = MARC.MATNR AND MATDOC.WERKS = MARC.WERKS",
		},
		{
			ID:               23,
			GroupNumber:      4,
			GroupName:        "4. Material Movements & Inventory Postings",
			SourceEntity:     "Material Movement",
			TargetEntity:     "Batch",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MATDOC.MATNR = Batch.MATNR AND MATDOC.WERKS = Batch.WERKS AND MATDOC.CHARG = Batch.CHARG",
		},
		{
			ID:               24,
			GroupNumber:      4,
			GroupName:        "4. Material Movements & Inventory Postings",
			SourceEntity:     "Batch",
			TargetEntity:     "Batch Stock",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MCHB.MATNR = Batch.MATNR AND MCHB.WERKS = Batch.WERKS AND MCHB.CHARG = Batch.CHARG",
		},
		{
			ID:               25,
			GroupNumber:      4,
			GroupName:        "4. Material Movements & Inventory Postings",
			SourceEntity:     "Material Movement",
			TargetEntity:     "Material Document",
			JoinType:         "INNER JOIN",
			LogicDescription: "MATDOC.MBLNR = MKPF.MBLNR AND MATDOC.MJAHR = MKPF.MJAHR",
		},

		// 5. Procurement: Requisition to Purchase Order
		{
			ID:               26,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "Purchase Requisition",
			TargetEntity:     "PO Item",
			JoinType:         "LEFT JOIN",
			LogicDescription: "EBAN.BANFN = EKPO.BANFN AND EBAN.BNFPO = EKPO.BNFPO",
		},
		{
			ID:               27,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "Purchase Requisition",
			TargetEntity:     "PR Account Assignment",
			JoinType:         "LEFT JOIN",
			LogicDescription: "EBAN.BANFN = EBKN.BANFN AND EBAN.BNFPO = EBKN.BNFPO",
		},
		{
			ID:               28,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "Supplier",
			TargetEntity:     "Purchase Order",
			JoinType:         "LEFT JOIN",
			LogicDescription: "LFA1.LIFNR = EKKO.LIFNR",
		},
		{
			ID:               29,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "Supplier",
			TargetEntity:     "Supplier Purchasing Data",
			JoinType:         "LEFT JOIN",
			LogicDescription: "LFA1.LIFNR = LFM1.LIFNR",
		},
		{
			ID:               30,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "Supplier",
			TargetEntity:     "Supplier Company Data",
			JoinType:         "LEFT JOIN",
			LogicDescription: "LFA1.LIFNR = LFB1.LIFNR",
		},
		{
			ID:               31,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "Purchase Order",
			TargetEntity:     "PO Item",
			JoinType:         "INNER JOIN",
			LogicDescription: "EKKO.EBELN = EKPO.EBELN",
		},
		{
			ID:               32,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "PO Item",
			TargetEntity:     "Schedule Line",
			JoinType:         "LEFT JOIN",
			LogicDescription: "EKPO.EBELN = EKET.EBELN AND EKPO.EBELP = EKET.EBELP",
		},
		{
			ID:               33,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "PO Item",
			TargetEntity:     "PO History",
			JoinType:         "LEFT JOIN",
			LogicDescription: "EKPO.EBELN = EKBE.EBELN AND EKPO.EBELP = EKBE.EBELP",
		},
		{
			ID:               34,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "PO Item",
			TargetEntity:     "PO Confirmation",
			JoinType:         "LEFT JOIN",
			LogicDescription: "EKPO.EBELN = EKES.EBELN AND EKPO.EBELP = EKES.EBELP",
		},
		{
			ID:               35,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "PO Item",
			TargetEntity:     "GRN",
			JoinType:         "LEFT JOIN",
			LogicDescription: "EKPO.EBELN = MATDOC.EBELN AND EKPO.EBELP = MATDOC.EBELP AND MATDOC.BWART is a goods-receipt movement",
		},
		{
			ID:               36,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "GRN",
			TargetEntity:     "Material Movement",
			JoinType:         "INNER JOIN",
			LogicDescription: "GRN references MATDOC.MBLNR + MATDOC.MJAHR + MATDOC.ZEILE",
		},
		{
			ID:               37,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "GRN",
			TargetEntity:     "Batch",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MATDOC.MATNR = Batch.MATNR AND MATDOC.WERKS = Batch.WERKS AND MATDOC.CHARG = Batch.CHARG",
		},
		{
			ID:               38,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "Reservation",
			TargetEntity:     "Purchase Requisition",
			JoinType:         "LEFT JOIN",
			LogicDescription: "RESB.BANFN = EBAN.BANFN AND RESB.BNFPO = EBAN.BNFPO",
		},
		{
			ID:               39,
			GroupNumber:      5,
			GroupName:        "5. Procurement: Requisition to Purchase Order",
			SourceEntity:     "Reservation",
			TargetEntity:     "Purchase Order",
			JoinType:         "LEFT JOIN",
			LogicDescription: "RESB.EBELN = EKPO.EBELN AND RESB.EBELP = EKPO.EBELP",
		},

		// 6. Bill of Materials & Routing
		{
			ID:               40,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "BOM Assignment",
			TargetEntity:     "Material",
			JoinType:         "INNER JOIN",
			LogicDescription: "MAST.MATNR = MARA.MATNR",
		},
		{
			ID:               41,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "BOM Assignment",
			TargetEntity:     "Plant Material",
			JoinType:         "INNER JOIN",
			LogicDescription: "MAST.MATNR = MARC.MATNR AND MAST.WERKS = MARC.WERKS",
		},
		{
			ID:               42,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "BOM Assignment",
			TargetEntity:     "BOM Header",
			JoinType:         "INNER JOIN",
			LogicDescription: "MAST.STLNR = STKO.STLNR AND MAST.STLAL = STKO.STLAL",
		},
		{
			ID:               43,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "BOM Header",
			TargetEntity:     "BOM Component",
			JoinType:         "LEFT JOIN",
			LogicDescription: "STKO.STLNR = STPO.STLNR",
		},
		{
			ID:               44,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "BOM Component",
			TargetEntity:     "Material",
			JoinType:         "INNER JOIN",
			LogicDescription: "STPO.IDNRK = MARA.MATNR",
		},
		{
			ID:               45,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "Material",
			TargetEntity:     "Routing Assignment",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MAPL.MATNR = MARA.MATNR AND MAPL.WERKS = MARC.WERKS",
		},
		{
			ID:               46,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "Routing Assignment",
			TargetEntity:     "Routing Header",
			JoinType:         "INNER JOIN",
			LogicDescription: "MAPL.PLNNR = PLKO.PLNNR AND MAPL.PLNAL = PLKO.PLNAL",
		},
		{
			ID:               47,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "Routing Header",
			TargetEntity:     "Routing Operation",
			JoinType:         "LEFT JOIN",
			LogicDescription: "PLKO.PLNNR = PLPO.PLNNR",
		},
		{
			ID:               48,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "Routing Operation",
			TargetEntity:     "Work Center",
			JoinType:         "INNER JOIN",
			LogicDescription: "PLPO.ARBID = CRHD.OBJID",
		},
		{
			ID:               49,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "Production Version",
			TargetEntity:     "Material",
			JoinType:         "INNER JOIN",
			LogicDescription: "MKAL.MATNR = MARA.MATNR",
		},
		{
			ID:               50,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "Production Version",
			TargetEntity:     "Plant Material",
			JoinType:         "INNER JOIN",
			LogicDescription: "MKAL.MATNR = MARC.MATNR AND MKAL.WERKS = MARC.WERKS",
		},
		{
			ID:               51,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "Production Version",
			TargetEntity:     "BOM",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MKAL.MATNR = MAST.MATNR AND MKAL.WERKS = MAST.WERKS AND MKAL.STLAL = MAST.STLAL",
		},
		{
			ID:               52,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "Production Version",
			TargetEntity:     "Routing",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MKAL.MATNR = MAPL.MATNR AND MKAL.WERKS = MAPL.WERKS AND MKAL.PLNNR = MAPL.PLNNR AND MKAL.PLNAL = MAPL.PLNAL",
		},
		{
			ID:               53,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "Process Order",
			TargetEntity:     "Production Version",
			JoinType:         "LEFT JOIN",
			LogicDescription: "AFKO.PLNNR = MKAL.PLNNR AND AFKO.PLNAL = MKAL.PLNAL where applicable",
		},
		{
			ID:               54,
			GroupNumber:      6,
			GroupName:        "6. Bill of Materials & Routing",
			SourceEntity:     "Process Order",
			TargetEntity:     "Routing",
			JoinType:         "LEFT JOIN",
			LogicDescription: "AFKO.PLNNR = PLKO.PLNNR AND AFKO.PLNAL = PLKO.PLNAL",
		},

		// 7. Sales & Distribution
		{
			ID:               55,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Sales Order",
			TargetEntity:     "Sales Order Item",
			JoinType:         "INNER JOIN",
			LogicDescription: "VBAK.VBELN = VBAP.VBELN",
		},
		{
			ID:               56,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Sales Order Item",
			TargetEntity:     "Material",
			JoinType:         "INNER JOIN",
			LogicDescription: "VBAP.MATNR = MARA.MATNR",
		},
		{
			ID:               57,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Sales Order Item",
			TargetEntity:     "Batch",
			JoinType:         "LEFT JOIN",
			LogicDescription: "VBAP.MATNR = Batch.MATNR AND VBAP.CHARG = Batch.CHARG when populated",
		},
		{
			ID:               58,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Sales Order",
			TargetEntity:     "Customer",
			JoinType:         "LEFT JOIN",
			LogicDescription: "VBAK.VBELN = VBPA.VBELN AND relevant customer partner function",
		},
		{
			ID:               59,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Sales Order",
			TargetEntity:     "Delivery",
			JoinType:         "LEFT JOIN",
			LogicDescription: "VBFA.VBELV = VBAK.VBELN AND VBFA.VBELN = LIKP.VBELN",
		},
		{
			ID:               60,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Sales Order Item",
			TargetEntity:     "Delivery Item",
			JoinType:         "LEFT JOIN",
			LogicDescription: "VBFA.VBELV = VBAP.VBELN AND VBFA.POSNV = VBAP.POSNR AND VBFA.VBELN = LIPS.VBELN AND VBFA.POSNN = LIPS.POSNR",
		},
		{
			ID:               61,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Delivery",
			TargetEntity:     "Delivery Item",
			JoinType:         "INNER JOIN",
			LogicDescription: "LIKP.VBELN = LIPS.VBELN",
		},
		{
			ID:               62,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Delivery Item",
			TargetEntity:     "Material",
			JoinType:         "INNER JOIN",
			LogicDescription: "LIPS.MATNR = MARA.MATNR",
		},
		{
			ID:               63,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Delivery Item",
			TargetEntity:     "Batch",
			JoinType:         "LEFT JOIN",
			LogicDescription: "LIPS.MATNR = Batch.MATNR AND LIPS.WERKS = Batch.WERKS AND LIPS.CHARG = Batch.CHARG",
		},
		{
			ID:               64,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Delivery Item",
			TargetEntity:     "Process Order",
			JoinType:         "LEFT JOIN",
			LogicDescription: "LIPS.AUFNR = AFKO.AUFNR when populated",
		},
		{
			ID:               65,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Delivery Item",
			TargetEntity:     "Goods Issue",
			JoinType:         "LEFT JOIN",
			LogicDescription: "LIPS.LFBNR = MATDOC.MBLNR AND LIPS.LFPOS = MATDOC.ZEILE AND LIPS.LFGJA = MATDOC.MJAHR",
		},
		{
			ID:               66,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Delivery Item",
			TargetEntity:     "Material Movement",
			JoinType:         "LEFT JOIN",
			LogicDescription: "Validate LIPS.MATNR = MATDOC.MATNR AND LIPS.WERKS = MATDOC.WERKS",
		},
		{
			ID:               67,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Billing",
			TargetEntity:     "Billing Item",
			JoinType:         "INNER JOIN",
			LogicDescription: "VBRK.VBELN = VBRP.VBELN",
		},
		{
			ID:               68,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Billing Item",
			TargetEntity:     "Delivery Item",
			JoinType:         "LEFT JOIN",
			LogicDescription: "VBRP.VGBEL = LIPS.VBELN AND VBRP.VGPOS = LIPS.POSNR",
		},
		{
			ID:               69,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Billing Item",
			TargetEntity:     "Sales Order Item",
			JoinType:         "LEFT JOIN",
			LogicDescription: "VBRP.AUBEL = VBAP.VBELN AND VBRP.AUPOS = VBAP.POSNR",
		},
		{
			ID:               70,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Billing",
			TargetEntity:     "Delivery",
			JoinType:         "LEFT JOIN",
			LogicDescription: "Use VBFA: billing document VBELN <-> preceding delivery VBELV",
		},
		{
			ID:               71,
			GroupNumber:      7,
			GroupName:        "7. Sales & Distribution",
			SourceEntity:     "Sales Document Flow",
			TargetEntity:     "Sales Documents",
			JoinType:         "INNER JOIN",
			LogicDescription: "VBFA.VBELV + VBFA.POSNV = preceding document/item; VBFA.VBELN + VBFA.POSNN = subsequent document/item",
		},

		// 8. Inventory, Batch & Material Master
		{
			ID:               72,
			GroupNumber:      8,
			GroupName:        "8. Inventory, Batch & Material Master",
			SourceEntity:     "Material",
			TargetEntity:     "Inventory",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MARA.MATNR = MARD.MATNR",
		},
		{
			ID:               73,
			GroupNumber:      8,
			GroupName:        "8. Inventory, Batch & Material Master",
			SourceEntity:     "Plant Material",
			TargetEntity:     "Inventory",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MARC.MATNR = MARD.MATNR AND MARC.WERKS = MARD.WERKS",
		},
		{
			ID:               74,
			GroupNumber:      8,
			GroupName:        "8. Inventory, Batch & Material Master",
			SourceEntity:     "Inventory",
			TargetEntity:     "Batch Stock",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MARD.MATNR = MCHB.MATNR AND MARD.WERKS = MCHB.WERKS AND MARD.LGORT = MCHB.LGORT",
		},
		{
			ID:               75,
			GroupNumber:      8,
			GroupName:        "8. Inventory, Batch & Material Master",
			SourceEntity:     "Material Movement",
			TargetEntity:     "Inventory",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MATDOC.MATNR = MARD.MATNR AND MATDOC.WERKS = MARD.WERKS AND MATDOC.LGORT = MARD.LGORT",
		},
		{
			ID:               76,
			GroupNumber:      8,
			GroupName:        "8. Inventory, Batch & Material Master",
			SourceEntity:     "Material Movement",
			TargetEntity:     "Reservation",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MATDOC.RSNUM = RESB.RSNUM AND MATDOC.RSPOS = RESB.RSPOS",
		},
		{
			ID:               77,
			GroupNumber:      8,
			GroupName:        "8. Inventory, Batch & Material Master",
			SourceEntity:     "Material Movement",
			TargetEntity:     "Purchase Order",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MATDOC.EBELN = EKPO.EBELN AND MATDOC.EBELP = EKPO.EBELP",
		},
		{
			ID:               78,
			GroupNumber:      8,
			GroupName:        "8. Inventory, Batch & Material Master",
			SourceEntity:     "Material Movement",
			TargetEntity:     "Process Order",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MATDOC.AUFNR = AFKO.AUFNR",
		},
		{
			ID:               79,
			GroupNumber:      8,
			GroupName:        "8. Inventory, Batch & Material Master",
			SourceEntity:     "Material Movement",
			TargetEntity:     "Sales Order Item",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MATDOC.KDAUF = VBAP.VBELN AND MATDOC.KDPOS = VBAP.POSNR",
		},
		{
			ID:               80,
			GroupNumber:      8,
			GroupName:        "8. Inventory, Batch & Material Master",
			SourceEntity:     "Batch",
			TargetEntity:     "Material",
			JoinType:         "INNER JOIN",
			LogicDescription: "MCHA.MATNR = MARA.MATNR",
		},
		{
			ID:               81,
			GroupNumber:      8,
			GroupName:        "8. Inventory, Batch & Material Master",
			SourceEntity:     "Batch",
			TargetEntity:     "Plant Material",
			JoinType:         "INNER JOIN",
			LogicDescription: "MCHA.MATNR = MARC.MATNR AND MCHA.WERKS = MARC.WERKS",
		},
		{
			ID:               82,
			GroupNumber:      8,
			GroupName:        "8. Inventory, Batch & Material Master",
			SourceEntity:     "Batch",
			TargetEntity:     "Batch Master",
			JoinType:         "INNER JOIN",
			LogicDescription: "MCHA.MATNR = MCH1.MATNR AND MCHA.CHARG = MCH1.CHARG",
		},

		// 9. Quality Management (Extended Linkages)
		{
			ID:               83,
			GroupNumber:      9,
			GroupName:        "9. Quality Management (Extended Linkages)",
			SourceEntity:     "Quality Inspection Lot",
			TargetEntity:     "Material Document",
			JoinType:         "LEFT JOIN",
			LogicDescription: "QALS.MBLNR = MATDOC.MBLNR AND QALS.MJAHR = MATDOC.MJAHR AND QALS.ZEILE = MATDOC.ZEILE",
		},
		{
			ID:               84,
			GroupNumber:      9,
			GroupName:        "9. Quality Management (Extended Linkages)",
			SourceEntity:     "Quality Inspection Lot",
			TargetEntity:     "Process Operation",
			JoinType:         "LEFT JOIN",
			LogicDescription: "QALS.AUFPL = AFVC.AUFPL when populated",
		},
		{
			ID:               85,
			GroupNumber:      9,
			GroupName:        "9. Quality Management (Extended Linkages)",
			SourceEntity:     "Quality Inspection Lot",
			TargetEntity:     "Process Order",
			JoinType:         "LEFT JOIN",
			LogicDescription: "QALS.AUFNR = AFKO.AUFNR when populated",
		},

		// 10. Sales & Delivery Cross-References
		{
			ID:               86,
			GroupNumber:      10,
			GroupName:        "10. Sales & Delivery Cross-References",
			SourceEntity:     "Delivery Item",
			TargetEntity:     "Sales Order Item",
			JoinType:         "LEFT JOIN",
			LogicDescription: "LIPS.VGBEL = VBAP.VBELN AND LIPS.VGPOS = VBAP.POSNR",
		},
		{
			ID:               87,
			GroupNumber:      10,
			GroupName:        "10. Sales & Delivery Cross-References",
			SourceEntity:     "Billing Item",
			TargetEntity:     "Sales Order Item",
			JoinType:         "LEFT JOIN",
			LogicDescription: "VBRP.AUBEL = VBAP.VBELN AND VBRP.AUPOS = VBAP.POSNR",
		},
		{
			ID:               88,
			GroupNumber:      10,
			GroupName:        "10. Sales & Delivery Cross-References",
			SourceEntity:     "Delivery Item",
			TargetEntity:     "Reservation",
			JoinType:         "LEFT JOIN",
			LogicDescription: "LIPS.RSNUM = RESB.RSNUM AND LIPS.RSPOS = RESB.RSPOS when populated",
		},

		// 11. Production Yield, Scrap & Confirmation
		{
			ID:               89,
			GroupNumber:      11,
			GroupName:        "11. Production Yield, Scrap & Confirmation",
			SourceEntity:     "Process Order",
			TargetEntity:     "Production Yield",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MATDOC.AUFNR = AFKO.AUFNR AND MATDOC.BWART = 101",
		},
		{
			ID:               90,
			GroupNumber:      11,
			GroupName:        "11. Production Yield, Scrap & Confirmation",
			SourceEntity:     "Process Order",
			TargetEntity:     "Production Scrap",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MATDOC.AUFNR = AFKO.AUFNR AND MATDOC.BWART corresponds to the configured scrap movement",
		},
		{
			ID:               91,
			GroupNumber:      11,
			GroupName:        "11. Production Yield, Scrap & Confirmation",
			SourceEntity:     "Production Confirmation",
			TargetEntity:     "Process Operation",
			JoinType:         "INNER JOIN",
			LogicDescription: "AFRU.AUFPL = AFVC.AUFPL AND AFRU.APLZL = AFVC.APLZL",
		},
		{
			ID:               92,
			GroupNumber:      11,
			GroupName:        "11. Production Yield, Scrap & Confirmation",
			SourceEntity:     "Production Confirmation",
			TargetEntity:     "Process Order",
			JoinType:         "INNER JOIN",
			LogicDescription: "AFRU.AUFNR = AFKO.AUFNR",
		},

		// 12. Goods Receipt (GRN) Linkages
		{
			ID:               93,
			GroupNumber:      12,
			GroupName:        "12. Goods Receipt (GRN) Linkages",
			SourceEntity:     "GRN",
			TargetEntity:     "Purchase Order Item",
			JoinType:         "INNER JOIN",
			LogicDescription: "MATDOC.MBLNR + MJAHR + ZEILE identifies GRN movement AND MATDOC.EBELN = EKPO.EBELN AND MATDOC.EBELP = EKPO.EBELP",
		},
		{
			ID:               94,
			GroupNumber:      12,
			GroupName:        "12. Goods Receipt (GRN) Linkages",
			SourceEntity:     "GRN",
			TargetEntity:     "Material",
			JoinType:         "INNER JOIN",
			LogicDescription: "MATDOC.MATNR = MARA.MATNR",
		},
		{
			ID:               95,
			GroupNumber:      12,
			GroupName:        "12. Goods Receipt (GRN) Linkages",
			SourceEntity:     "GRN",
			TargetEntity:     "Inventory",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MATDOC.MATNR = MARD.MATNR AND MATDOC.WERKS = MARD.WERKS AND MATDOC.LGORT = MARD.LGORT",
		},
		{
			ID:               96,
			GroupNumber:      12,
			GroupName:        "12. Goods Receipt (GRN) Linkages",
			SourceEntity:     "GRN",
			TargetEntity:     "Batch",
			JoinType:         "LEFT JOIN",
			LogicDescription: "MATDOC.MATNR = Batch.MATNR AND MATDOC.WERKS = Batch.WERKS AND MATDOC.CHARG = Batch.CHARG",
		},

		// 13. Sales Returns
		{
			ID:               97,
			GroupNumber:      13,
			GroupName:        "13. Sales Returns",
			SourceEntity:     "Sales Return",
			TargetEntity:     "Sales Document Flow",
			JoinType:         "INNER JOIN",
			LogicDescription: "VBFA.VBELV + VBFA.POSNV = preceding sales/delivery/billing document/item AND VBFA.VBELN + VBFA.POSNN = return document/item",
		},
		{
			ID:               98,
			GroupNumber:      13,
			GroupName:        "13. Sales Returns",
			SourceEntity:     "Sales Return",
			TargetEntity:     "Sales Order",
			JoinType:         "LEFT JOIN",
			LogicDescription: "VBFA.VBELV = VBAK.VBELN / relevant return-document flow relationship",
		},
		{
			ID:               99,
			GroupNumber:      13,
			GroupName:        "13. Sales Returns",
			SourceEntity:     "Sales Return",
			TargetEntity:     "Sales Order Item",
			JoinType:         "LEFT JOIN",
			LogicDescription: "VBFA.VBELV = VBAP.VBELN AND VBFA.POSNV = VBAP.POSNR / relevant return-document flow relationship",
		},
		{
			ID:               100,
			GroupNumber:      13,
			GroupName:        "13. Sales Returns",
			SourceEntity:     "Sales Return",
			TargetEntity:     "Delivery",
			JoinType:         "LEFT JOIN",
			LogicDescription: "VBFA.VBELV = LIKP.VBELN / relevant return-delivery document flow relationship",
		},
		{
			ID:               101,
			GroupNumber:      13,
			GroupName:        "13. Sales Returns",
			SourceEntity:     "Sales Return",
			TargetEntity:     "Delivery Item",
			JoinType:         "LEFT JOIN",
			LogicDescription: "VBFA.VBELV = LIPS.VBELN AND VBFA.POSNV = LIPS.POSNR / relevant return-delivery flow relationship",
		},
		{
			ID:               102,
			GroupNumber:      13,
			GroupName:        "13. Sales Returns",
			SourceEntity:     "Sales Return",
			TargetEntity:     "Billing Document",
			JoinType:         "LEFT JOIN",
			LogicDescription: "VBFA.VBELV = VBRK.VBELN / relevant return-billing document flow relationship",
		},
		{
			ID:               103,
			GroupNumber:      13,
			GroupName:        "13. Sales Returns",
			SourceEntity:     "Sales Return",
			TargetEntity:     "Billing Item",
			JoinType:         "LEFT JOIN",
			LogicDescription: "VBFA.VBELV = VBRP.VBELN AND VBFA.POSNV = VBRP.POSNR / relevant return-billing flow relationship",
		},
		{
			ID:               104,
			GroupNumber:      13,
			GroupName:        "13. Sales Returns",
			SourceEntity:     "Sales Return",
			TargetEntity:     "Material Movement",
			JoinType:         "LEFT JOIN",
			LogicDescription: "Where return is posted through inventory: identify return material document in MATDOC; validate MATDOC.MATNR = LIPS.MATNR and MATDOC.WERKS = LIPS.WERKS",
		},
		{
			ID:               105,
			GroupNumber:      13,
			GroupName:        "13. Sales Returns",
			SourceEntity:     "Sales Return",
			TargetEntity:     "Batch",
			JoinType:         "LEFT JOIN",
			LogicDescription: "For batch-specific return, LIPS.MATNR = Batch.MATNR AND LIPS.WERKS = Batch.WERKS AND LIPS.CHARG = Batch.CHARG",
		},
		{
			ID:               106,
			GroupNumber:      13,
			GroupName:        "13. Sales Returns",
			SourceEntity:     "Sales Return",
			TargetEntity:     "Customer",
			JoinType:         "LEFT JOIN",
			LogicDescription: "Resolve customer through related sales document: VBPA.VBELN = related sales document VBELN AND relevant customer partner function",
		},
	}
}
